version: "3.9"

services:
  arangodb:
    image: arangodb/arangodb:latest
    container_name: arangodb
    restart: unless-stopped

    ports:
      - "8529:8529"

    environment:
      ARANGO_ROOT_PASSWORD: password

    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
      - ./cache:/cache

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-IoTKG
    ports:
      - "4000:8080"
    environment:
      - OPENAI_API_KEY=none
  
  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "9000:9000"
    command: ["bash", "startup_script.sh"]

volumes:
  arangodb_data:
  arangodb_apps:
