from .amazon import AMAZON_SELECTOR, AMAZON_PRODUCT_URL_SELECTOR
from .best_buy import BEST_BUY_SELECTOR ,BEST_BUY_PRODUCT_URL_SELECTOR
from .costco import COSTCO_SELECTOR, COSTCO_PRODUCT_URL_SELECTOR
from .home_depot import HOME_DEPOT_PRODUCT_URL_SELECTOR
from .sams_club import SAMS_CLUB_PRODUCT_URL_SELECTOR
from .target import TARGET_SELECTOR ,TARGET_PRODUCT_URL_SELECTOR
from .walmart import WALMART_SELECTOR, WALMART_PRODUCT_URL_SELECTOR

from .search_queries import search_queries

__all__ = [
    'AMAZON_SELECTOR',
    'AMAZON_PRODUCT_URL_SELECTOR',
    'BEST_BUY_SELECTOR',
    'BEST_BUY_PRODUCT_URL_SELECTOR',
    'COSTCO_SELECTOR',
    'COSTCO_PRODUCT_URL_SELECTOR',
    'HOME_DEPOT_PRODUCT_URL_SELECTOR',
    'SAMS_CLUB_PRODUCT_URL_SELECTOR',
    'TARGET_SELECTOR',
    'TARGET_PRODUCT_URL_SELECTOR',
    'WALMART_SELECTOR',
    'WALMART_PRODUCT_URL_SELECTOR',
    'search_queries'
]